- name: openai/claude-3.5-sonnet
  edit_format: diff
  weak_model_name: openai/gemini-2.0-flash-001
  use_repo_map: true
  examples_as_sys_msg: true
  editor_model_name: openai/claude-3.5-sonnet
  editor_edit_format: editor-diff

- name: openai/claude-3.7-sonnet
  edit_format: diff
  weak_model_name: openai/gemini-2.0-flash-001
  use_repo_map: true
  examples_as_sys_msg: true
  editor_model_name: openai/claude-3.7-sonnet
  editor_edit_format: editor-diff

- name: openai/claude-3.7-sonnet-thought
  edit_format: diff
  weak_model_name: openai/gemini-2.0-flash-001
  use_repo_map: true
  examples_as_sys_msg: true
  editor_model_name: openai/claude-3.7-sonnet
  editor_edit_format: editor-diff
